name: traffic-detector

on:
  schedule:            # UTC → */5 代表每 5 分鐘跑一次
    - cron: '*/5 * * * *'
  workflow_dispatch:   # 允許手動執行

jobs:
  run:
    runs-on: ubuntu-latest

    steps:
      # 1. 取出程式碼
      - uses: actions/checkout@v4

      # 2. 安裝 Python 3.11
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      # 3. 安裝套件
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r detector/requirements.txt

      # -------（若直播需要 Cookies，取消註解以下 4~5 行）-------
      # - name: Decode YouTube cookies
      #   run: echo "${{ secrets.YT_COOKIES_B64 }}" | base64 -d > youtube_cookies.txt
      # ------------------------------------------------------------

      # 4. 執行 YOLO 偵測並產生 docs/index.html
      - name: Run YOLO detector & update site
        run: python detector/detect.py

      # 5. 有變更就自動 commit + push
      - name: Commit and push if something changed
        run: |
          git config --global user.email "action@github.com"
          git config --global user.name  "traffic-bot"
          git add data/ docs/index.html
          if ! git diff --cached --quiet; then
            git commit -m "auto: update traffic $(date -u +'%Y-%m-%d %H:%M')"
            git push
          fi
